### ISSUE TITLE
Accessing a server while not being whitelisted makes the Discord Rich Presence plugin display wrong information

### ISSUE THREAD

**Issue by bmx22c** [openplanet-nl/issues#15] opened 2021-11-07 14:01 UTC
Hello !
I discovered a bug with the Discord Rich Presence plugin.
If you try to access a server that have the [PyPlanet whitelist plugin](https://github.com/micm0/pyplanet_whitelist) installed and you aren't whitelisted, the server will kick you on connection and will return you to the main menu. What happens is that the plugin will still display that you are on the server even tho you are back on the main menu.
You can look at the file `__init__.py` in the `whitelist` folder, starting at line 52.

You can test this bug on the Sportyx Cup server with current password `checktotd`. The password will change on the next friday tho so you may need to check Yannex Discord in `🔑 password` channel.

![image](https://user-images.githubusercontent.com/6803869/140648135-45e7601e-c102-4d68-9e65-9900257c6957.png)
![image](https://user-images.githubusercontent.com/6803869/140648137-112f9eff-888d-4db5-b452-26225a57f575.png)

**Comment by codecat** [comment] 2021-11-21 13:54
The server doesn't have a whitelist activated right now, so I can't really test this. Is there any other server with this?

**Comment by codecat** [comment] 2021-12-13 14:38
With @Nsgr's help, I tried this on the Shitfest server and I couldn't reproduce this. I'll close this for now, but let me know if you want me to look at this again.

**Closed as completed by codecat** 2021-12-13 14:38 UTC
Labels: bug
